version: '2'
services:
  rails-image:
    build:
      context: .
    volumes:
      - .:/railsapp
  db:
    image: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
  web:
    image: railsapp_rails-image
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes_from:
      - rails-image
    ports:
      - "3000:3000"
      - "1236:1236"
    depends_on:
      - rails-image
      - db
      - redis
  worker:
    image: railsapp_rails-image
    command: bundle exec rake resque:work QUEUE="*"
    volumes_from:
      - rails-image
    depends_on:
      - rails-image
      - db
      - redis